name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  lint:
    name: Pre-commit Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.2.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.8.1
      - name: Install repository
        # needed for generate-col-ops hook
        run: pixi run postinstall
      - name: pre-commit
        run: pixi run pre-commit run -a --color=always --show-diff-on-failure
      - name: Check pyproject.toml dependencies
        run: pixi run check-deps
  test:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        environment:
          - py311
          - py314
          - py311all
          - py312all
          - py313all
          - py314all
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: ${{ matrix.environment }}

      - name: Run tests
        run: |
          pixi run -e ${{ matrix.environment }} pytest tests -ra ${RUNNER_DEBUG:+-v} --color=yes
